const Settings = {
  gender: ['m', 'f'],
  langs: [
            "spanish",
            "polish",
            "slovene",
            "jewish",
            "finnish",
            "japanese",
            "croatian",
            "italian",
            "",
            "english",
            "welsh",
            "esperanto",
            "hungarian",
            "scandinavian",
            "danish",
            "swedish",
            "norwegian",
            "indian",
            "irish",
            "scottish",
            "french",
            "vietnamese",
            "romanian",
            "history",
            "dutch",
            "portuguese",
            "german",
            "biblical",
            "greek",
            "african",
            "turkish",
            "literature",
            "ancient egyptian",
            "basque",
            "ancient greek",
            "norse mythology",
            "roman mythology",
            "arabic",
            "greek mythology",
            "ancient roman",
            "russian",
            "czech",
            "armenian",
            "serbian",
            "bulgarian",
            "khmer",
            "ancient celtic",
            "latvian",
            "icelandic",
            "lithuanian",
            "hindu mythology",
            "manx",
            "slavic mythology",
            "native american",
            "chinese",
            "hawaiian",
            "maori",
            "anglo-saxon mythology",
            "ukrainian",
            "germanic mythology",
            "anglo-saxon",
            "galician",
            "new world mythology",
            "?",
            "theology",
            "breton",
            "iranian",
            "welsh mythology",
            "judeo-christian legend",
            "late roman",
            "irish mythology",
            "catalan",
            "celtic mythology",
            "ancient germanic",
            "astronomy",
            "estonian",
            "frisian",
            "near eastern mythology",
            "cornish",
            "slovak",
            "provençal",
            "thai",
            "egyptian mythology",
            "ancient scandinavian",
            "far eastern mythology",
            "korean",
            "macedonian",
            "albanian",
            "medieval english"
          ]
}